Repository VATSIM-UK/core, pull requests merged in 2018-03, with the labels that each got.

#1148 Apply fixes from StyleCI
  app/Console/Commands/Feedback/GenerateFeedbackSummary.php
  app/Http/Controllers/Adm/AdmController.php
  app/Http/Controllers/Adm/Mship/Feedback.php
  app/Http/Requests/Mship/Feedback/NewFeedbackFormRequest.php
  app/Http/Requests/Mship/Feedback/UpdateFeedbackFormRequest.php
  app/Models/Mship/Feedback/Question/Type.php
  database/migrations/2018_03_01_211706_feedback_slug_length_and_permission.php
Labels: styleci

#1151 CORE-39 - Restart FTE Tour
  resources/views/fte/dashboard.blade.php
Labels: module - smartcars

#1157 Hotfix 3.6.6 - Fix Importing Member Emails
  app/Console/Commands/Members/ImportMembers.php
Labels: bug
