Repository VATSIM-UK/core, pull requests merged in 2018-02, with the labels that each got.

#1117 Change complete button colour
  resources/views/visit-transfer/admin/application/view.blade.php
Labels: feature request, module - visit-transfer

#1133 Apply fixes from StyleCI
  app/Http/Controllers/Adm/Mship/Account.php
Labels: styleci

#1138 Apply fixes from StyleCI
  app/Http/Controllers/Smartcars/Api/Router.php
  app/Http/Controllers/Smartcars/SmartcarsController.php
  database/migrations/2018_02_27_094211_normalise_smartcars_permission_names.php
Labels: styleci

#1136 Hotfix: Accommodate slugs in permissions
  app/Models/Mship/Role.php
Labels: bug, critical

#1142 Apply fixes from StyleCI
  database/migrations/2018_02_28_201745_add_privacc_contact.php
Labels: styleci
